Update classes to be PSR-4 compliant
silverstripe/silverstripe-segment-field pull request #104
Opened 2024-04-02 01:36 UTC by Cambis

Resolves #103 

- Update `autoload` configuration in `composer.json`
- Update namespacing for classes in `tests/SegmentFieldModifier`
- Add .gitattributes file

2024-04-02 21:04 UTC, GuySartorelli requested changes
I've added the pull request template back into your PR description (it should have been there before - did you delete it?)
Please fill it in completely including ticking any checkboxes that apply.

2024-04-02 21:04 UTC, GuySartorelli commented on composer.json
> +    }
```suggestion
```
This isn't necessary for modules

2024-04-02 21:04 UTC, GuySartorelli commented on composer.json
> +    "autoload-dev": {
`autoload-dev` will cause problems when running tests locally if the module was installed into the vendor directory of an existing project (which is how the CMS Squad works most of the time).
It also prevents us from running these tests in conjunction with other modules e.g. as part of recipe-kitchen-sink.

Please revert this change.

2024-04-05 02:59 UTC, Cambis commented
Addressed the changes @GuySartorelli, apologies this is my first time contributing to silverstripe. Still very excited :smiley:

2024-04-05 03:14 UTC, GuySartorelli commented
No apology necessary, you've done great! Thanks for submitting this. Just letting ci run, if it goes green I'll be happy to merge this in.

2024-04-05 07:02 UTC, GuySartorelli approved these changes

2024-04-05 07:02 UTC, merged